### ISSUE TITLE
https://drive.google.com/open?id=1uyTMejyhpkPD8L-v8JJ9JOECrEIYZPCI is not valid

### ISSUE THREAD

**Issue by smallapes** [pse-ecn/pose-sensitive-embedding#10]

**Comment by ssarfraz** [comment]
yes, have removed the features for a while, as I needed space on my drive.  Have uploaded it again here
https://drive.google.com/drive/folders/18eZlJIB5_WZ0tAa_SLbMJqxQS3C_76wh?usp=sharing

**Comment by rahuja123** [comment]
@ssarfraz 
Is there a pre-trained model available through which we can find out the features ourselves?

**Comment by ssarfraz** [comment]
@rahuja123 , you can download the trained PSE model files for Market and Duke here

https://bwsyncandshare.kit.edu/dl/fiVyQmjBRDtJ9NzxuEqbSBn1/.zip

**Comment by ri-sal** [comment]
Hi,

I tried to run the predictor_preid.py on the model provided in the PSE model files for Martket like this:


python3 predictor_preid.py --model-dir='PSE_tfModels'  --data='/mnt/Datasets/Incoming/Surveillance/PRID/Market-1501/data/Market-1501-v15.09.15/' --dataset-name=market1501 --batch-size=128 --network-name=resnet_v1_50_views

I'm getting the following errors:


InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [7,7,3,64] rhs shape= [7,7,17,64]
         [[Node: save/Assign_382 = Assign[T=DT_FLOAT, _class=["loc:@resnet_v1_50/conv1/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](resnet_v1_50/conv1/weights, save/RestoreV2_382/_777)]]

ERROR:tensorflow:==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Tensor'>):
<tf.Tensor 'report_uninitialized_variables_1/boolean_mask/Gather:0' shape=(?,) dtype=string>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
['File "predictor_preid.py", line 187, in <module>\n    main()', 'File "predictor_preid.py", line 181, in main\n    start_prediction(args.data_directory, args.dataset_name, args.model_dir, args.network_name, args.batch_size, args.batch_threads, args.num_classes, args.distractors)', 'File "predictor_preid.py", line 33, in start_prediction\n    run_prediction_and_evaluation(batch_size, batch_threads, dataset_factory, estimator, image_size, distractors)', 'File "predictor_preid.py", line 56, in run_prediction_and_evaluation\n    run_prediction_and_store_features(dataset_factory, batch_size, batch_threads, estimator, output_directory, \'test\', image_size)', 'File "predictor_preid.py", line 109, in run_prediction_and_store_features\n    for sample, prediction in enumerate(predicted):', 'File "/home/srl4hi/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 347, in predict\n    hooks=hooks) as mon_sess:', 'File "/home/srl4hi/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 668, in __init__\n    stop_grace_period_secs=stop_grace_period_secs)', 'File "/home/srl4hi/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 490, in __init__\n    self._sess = _RecoverableSession(self._coordinated_creator)', 'File "/home/srl4hi/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 842, in __init__\n    _WrappedSession.__init__(self, self._create_session())', 'File "/home/srl4hi/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 847, in _create_session\n    return self._sess_creator.create_session()', 'File "/home/srl4hi/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 551, in create_session\n    self.tf_sess = self._session_creator.create_session()', 'File "/home/srl4hi/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 416, in create_session\n    self._scaffold.finalize()', 'File "/home/srl4hi/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 196, in finalize\n    default_ready_for_local_init_op)', 'File "/home/srl4hi/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 258, in get_or_default\n    op = default_constructor()', 'File "/home/srl4hi/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 193, in default_ready_for_local_init_op\n    variables.global_variables())', 'File "/home/srl4hi/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/tf_should_use.py", line 175, in wrapped\n    return _add_should_use_warning(fn(*args, **kwargs))', 'File "/home/srl4hi/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/tf_should_use.py", line 144, in _add_should_use_warning\n    wrapped = TFShouldUseWarningWrapper(x)', 'File "/home/srl4hi/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/tf_should_use.py", line 101, in __init__\n    stack = [s.strip() for s in traceback.format_stack()]']
==================================


Please advise, thanks!
