### ISSUE TITLE
RAP Dataset

### ISSUE THREAD

**Issue by ri-sal** [pse-ecn/pose-sensitive-embedding#11]
Hi, I was wondering if a re-mapped version of the RAP dataset is being used for the View Predictor? 

I am unable to find 'train_list_52.txt' in the zip file provided by the RAP authors.

Thanks.

**Comment by ssarfraz** [comment]
@ri-sal  , Hi , I have added the RAP list files in the datasets here

https://github.com/pse-ecn/pose-sensitive-embedding/tree/master/datasets

**Comment by ri-sal** [comment]
Thank you!
