### ISSUE TITLE
I encounter "InvalidArgumentError" when I predict the model

### ISSUE THREAD

**Issue by THHHomas** [pse-ecn/pose-sensitive-embedding#15]
I download the pretrained model and use the command "python predictor_preid.py --model-dir=./models --data=./Data/Market-1501-v15.09.15  --dataset-name=market1501 --batch-size=128 --network-name=resnet_v1_50_views"
more, I write my checkpoint file like this:
model_checkpoint_path: "model.ckpt-104801"
all_model_checkpoint_paths: "model.ckpt-104801"

and i encounter the following error:
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [7,7,3,64] rhs shape= [7,7,17,64]
	 [[Node: save/Assign_382 = Assign[T=DT_FLOAT, _class=["loc:@resnet_v1_50/conv1/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](resnet_v1_50/conv1/weights, save/RestoreV2/_777)]]

**Comment by cppntn** [comment]
@THHHomas hello, I am facing the same error! How did you overcome it?

**Comment by THHHomas** [comment]
@antocapp , you need to get the pose map which is 17 channels feature before you use this program, please refer to [ https://github.com/pse-ecn/pose-sensitive-embedding/issues/13](this)
