### ISSUE TITLE
Problem about Mars dataset

### ISSUE THREAD

**Issue by SpiritBear000** [pse-ecn/pose-sensitive-embedding#21]
Hi! When i read your code,i am confused about why there isn't 'query' data in your Mars data prepare func.  I think this must be caused by my carelessness. But I really can't find it. So,could you please help me.

https://github.com/pse-ecn/pose-sensitive-embedding/blob/ebb032608267f3a098ec2e7f85935cc57860adfa/datasets/MarsDataset.py#L19

**Comment by ssarfraz** [comment]
the query and test set are prepared later in the official evaluation script provided by MARS.
