### ISSUE TITLE
Use your pretrained model for feature extraction only

### ISSUE THREAD

**Issue by cppntn** [pse-ecn/pose-sensitive-embedding#22]
Hello, thanks for this excellent work.
Is there a way to use your pretrained model for features extraction only? I want to test it on frames of a video, so only some detections should be feed into the network for each frame.

Thanks!

**Comment by ssarfraz** [comment]
you only need to to prepare your data loader for this. look into predictor_preid.py, on changing stuff so ti only writes the features. Also see how the data is fed through one of the datasets.py files, may it would be easy to just follow a similar read.
