### ISSUE TITLE
invalid argument : --initial-checkpoint

### ISSUE THREAD

**Issue by ravi7248** [pse-ecn/pose-sensitive-embedding#28]
I am training your project on Restnet-50 Baseline on Market1501 and I have replaced <> all values with directories but it's giving error as invalid argument.
First, I made a directory named **output** and gave path in **--output=<>**
Second, I made a directory named checkpoint and downloaded **inception -v4** and **ResNet V1 50** checkpoints and tried giving path in **--inital-checkpoint** but still it's giving error as **invalid argument --initial checkpoint**.
Can you tell I am following correct steps or not and if not then can you tell me what will the correct step to run it.
I am attaching screenshot as well.
![Screenshot (17)](https://user-images.githubusercontent.com/32006408/68546166-bd8b8980-03f9-11ea-85d3-61291b773f1b.png)

**Comment by ssarfraz** [comment]
check your spelling of initial-checkpoint (you have inital-checkpoint -- missing an i)

**Comment by ravi7248** [comment]
> check your spelling of initial-checkpoint (you have inital-checkpoint -- missing an i)

sorry for such a stupid mistake.

**Comment by ravi7248** [comment]
Actually I am trying to your project second and I am facing same issue both time and got stuck and I am not able to figure where is probelm.

python trainer_preid.py --output=c:\Users\user_name\Documents\pose-sensitive-embedding-master\output --data=c:\Users\user_name\Documents\pose-sensitive-embedding-master\datasets\Market-1501 --dataset-name=market1501 --batch-size=16 --num-epochs=100 --network-name=resnet_v1_50 --initial-checkpoint=c:\Users\user_name\Documents\pose-sensitive-embedding-master\checkpoint --checkpoint-exclude-scopes=resnet_v1_50/logits --trainable-scopes=resnet_v1_50/logits --no-evaluation.

**TypeError: Input 'filename' of 'ReadFile' Op has type float32 that does not match expected type of string.**
![Screenshot (18)](https://user-images.githubusercontent.com/32006408/68549003-62698f00-0419-11ea-8136-e765dc7008bf.png)
