### ISSUE TITLE
How to training the Views Predictor

### ISSUE THREAD

**Issue by xmlin1995** [pse-ecn/pose-sensitive-embedding#3]
First of all,thank you for release the code.When I training the Views Predictor,there is a error message that No such file or directory:'data_directory_RAP/train_list_52.txt'.There are two folders under the folder data_directory_RAP, RAP_annotation and RAP_dataset, respectively.
![tim 20180110195803](https://user-images.githubusercontent.com/29965528/34771733-99037bcc-f640-11e7-8c3c-ebbf898a87b4.png)

**Comment by huangzhenjie** [comment]
Have you solved this problem?@xmlin1995

**Comment by ri-sal** [comment]
Hi, I am also having the same issue. Do you have any solution?
