### ISSUE TITLE
where is the 'three consecutive convo-lutions with step sizes 2, 2, and 5' ?

### ISSUE THREAD

**Issue by datar001** [pse-ecn/pose-sensitive-embedding#36]
hi , when i read the code, i can't find the the 'three consecutive convo-lutions with step sizes 2, 2, and 5' mentioned in the paper, could you tell me where it was called。it can't be found in the resnet_v1_views.py.  Thanks very much

**Comment by datar001** [comment]
This the original paragraph in the paper.
![image](https://user-images.githubusercontent.com/62345916/79070000-2ce90a80-7d05-11ea-83fb-0dd3d3d75654.png)

**Comment by ssarfraz** [comment]
Look here https://github.com/pse-ecn/pose-sensitive-embedding/blob/master/nets/resnet_utils_views.py#L199

**Comment by datar001** [comment]
thanks very much. besides, i have a question Whether the number of input channels affects the model and how?. I utilize the Joint Body Parsing with 19 channels as ﬁne-grained information, making input images with 22 channels. But the final performance of the Pose Map Models is not particularly well (map:57.9, rank1:80.7), lower than the results i get in the exposed method(map:64.1, rank1:84.1). can you give me some suggestions? or what i should watch out for?

**Comment by ssarfraz** [comment]
I guess utilizing more joint locations in the input should not worsen the performance.. Not sure but may be try fine tuning the conv1 first sufficiently before fine tuning the full model.

**Comment by datar001** [comment]
I'm sorry to bother again. can you tell me where is the 'pose_maps/poses_maps.npy' in the RapPoseMapsDataset.py? it looks like lossing the file when i fine-tune the View Predictor in PSE model. I have generated the pose-map-file of RAP.  Thanks very much.
