### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by Rheelt** [pse-ecn/pose-sensitive-embedding#5]
i use python3.5 and tenorflow1.3.0, when i run python3 trainer_preid.py --output=./output --data=./datasets --dataset-name=market1501 --batch-size=16 --num-epochs=100 --network-name=resnet_v1_50  --trainable-scopes=resnet_v1_50/logits --no-evaluation
**The error message is as follows**
ValueError: Tensor conversion requested dtype string for Tensor with dtype float32: 'Tensor("input_producer/Gather:0", shape=(), dtype=float32, device=/device:CPU:0)'
TypeError: Input 'filename' of 'ReadFile' Op has type float32 that does not match expected type of string.

I really hope you can help me to figure it out. Thank you.

**Comment by SWRDFK** [comment]
I have met this problem before. You should download Market-1501 dataset and put it under the file 'datasets'.
