### ISSUE TITLE
how to specify the --no-evaluation flag

### ISSUE THREAD

**Issue by huangzhenjie** [pse-ecn/pose-sensitive-embedding#8]
Hi,

you work is so great. When I try to run your code, The error I encountered was ''ModuleNotFoundError: No module named 'matlab''', I want to ask that should I must install matlab in linxu to run the code? can I specify the --no-evaluation flag to avoid use Market1501 matlab evaluation script?

Thanks, have a good day.

**Comment by swg209** [comment]
@huangzhenjie  I also meet the same problem, It must  install matlab or not?
