### ISSUE TITLE
Training the Views Predictor

### ISSUE THREAD

**Issue by huangzhenjie** [pse-ecn/pose-sensitive-embedding#9]
hi,

Thank the author, you job is so great. I want to ask that when I want to Training the Views Predictor, should I need to download RAP datatsets and modify --dataset-name=market1501 to --datatset-name=rap. Because I am a bit puzzled when I see the command"python3 trainer_views.py --output=<output directory> --data=<dataset directory> --dataset-name=market1501 ".

Thank you.

**Comment by SWRDFK** [comment]
@huangzhenjie  hi, I'm doing the same thing with you. 
When I use "--dataset-name=market1501", I meet the problem "TypeError: Input 'filename' of 'ReadFile' Op has type float32 that does not match expected type of string.". I think it means there is something wrong with the dataset's path or name.
As for "--dataset-name=rap", the trouble is  "FileNotFoundError: [Errno 2] No such file or directory: './datasets/RAP_dataset/train_list_52.txt." RAP dataset truly has no such file, but FILE_BY_PART in RapDataset.py specifies 'train' as 'train_list_52.txt'.
So how do you think? Please inform me if you make some progress.
Thank you!

**Comment by huangzhenjie** [comment]
@SWRDFK I try to download the Rap dataset and use "--dataset-name=rap" to train it, you can download it in http://rap.idealtest.org/ , but the author of the data set has not replied to me.

**Comment by SWRDFK** [comment]
@huangzhenjie  I sent the author e-mail and he replied me, so you can wait for him or I give the dataset to you.

**Comment by huangzhenjie** [comment]
@SWRDFK I just sent an email to him an hour ago. My email is 761005190@qq.com, if you give me dataset, I promise i just use this dataset for training the Views Predictor.

**Comment by TJJTJJTJJ** [comment]
@SWRDFK  Hi， I have sent an email to him in the morning, but the author has not replied to me. So may you give the RAP data to me, I promise the dataset only for research on this. Thank you again. My email is 17120413@bjtu.edu.cn

**Comment by ri-sal** [comment]
@SWRDFK 

did you find out where the missing file (train_list_52.txt) is?

**Comment by wenjie710** [comment]
@SWRDFK Sorry to bother you. Could please send me the RAP dataset? I sent an email to the author two days ago but didn't get a reply. I promise you that I will only use it on research. Thanks a lot. (my email address is dingding@stu.xjtu.edu.cn

**Comment by SWRDFK** [comment]
@wenjie710  I sent it to your email last evening

**Comment by aaaadfghtf** [comment]
@SWRDFK Sorry to bother you. Could please send me the RAP dataset. I promise you that I will only use it on research. Thanks a lot. (my email address is 3022272930@qq.com.)
